# Generated by Django 5.0.6 on 2024-06-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobDBModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                ("inputs", models.JSONField(null=True)),
                ("outputs", models.JSONField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("errors", models.JSONField(null=True)),
                (
                    "previous_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="next_jobs",
                        to="django_async_job_pipelines.jobdbmodel",
                    ),
                ),
            ],
            options={
                "db_table": "async_job",
            },
        ),
    ]
