# Generated by Django 5.0.6 on 2024-06-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdbmodel",
            name="errors",
            field=models.TextField(null=True),
        ),
    ]
