# Generated by Django 5.0.6 on 2024-06-15 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0003_rename_errors_jobdbmodel_error"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobdbmodel",
            index=models.Index(fields=["status"], name="async_job_status_567d77_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdbmodel",
            index=models.Index(fields=["id", "status"], name="async_job_id_f1f327_idx"),
        ),
    ]
