# Generated by Django 5.0.6 on 2024-06-15 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_async_job_pipelines",
            "0004_jobdbmodel_async_job_status_567d77_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="jobdbmodel",
            name="async_job_status_567d77_idx",
        ),
        migrations.RemoveIndex(
            model_name="jobdbmodel",
            name="async_job_id_f1f327_idx",
        ),
    ]
