# Generated by Django 5.0.6 on 2024-06-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "django_async_job_pipelines",
            "0007_remove_jobdbmodel_async_job_status_567d77_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                            ("ERROR", "Error"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
