# Generated by Django 5.0.6 on 2024-07-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0008_pipeline"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pipeline",
            new_name="PipelineDBModel",
        ),
        migrations.AlterField(
            model_name="jobdbmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_READY", "Not Ready"),
                    ("NEW", "New"),
                    ("IN_PROGRESS", "In Progress"),
                    ("DONE", "Done"),
                    ("ERROR", "Error"),
                ],
                default="NEW",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="pipelinedbmodel",
            table="async_pipeline",
        ),
    ]
