# Generated by Django 5.0.6 on 2024-07-08 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0009_rename_pipeline_pipelinedbmodel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineJobs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_async_job_pipelines.jobdbmodel",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_async_job_pipelines.pipelinedbmodel",
                    ),
                ),
            ],
        ),
    ]
