# Generated by Django 5.0.6 on 2024-07-08 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0010_pipelinejobs"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="pipelinejobs",
            table="async_pipeline_jobs",
        ),
    ]
