# Generated by Django 5.0.6 on 2024-07-08 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0011_alter_pipelinejobs_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PipelineJobs",
            new_name="PipelineJobsDBModel",
        ),
    ]
