# Generated by Django 5.1.3 on 2024-12-16 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0012_rename_pipelinejobs_pipelinejobsdbmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelinejobsdbmodel",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="django_async_job_pipelines.pipelinedbmodel",
            ),
        ),
    ]
