# Generated by Django 5.1.4 on 2024-12-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0013_alter_pipelinejobsdbmodel_pipeline"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobdbmodel",
            index=models.Index(fields=["status"], name="async_job_status_567d77_idx"),
        ),
    ]
