# Generated by Django 5.1.3 on 2025-01-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_async_job_pipelines", "0014_jobdbmodel_async_job_status_567d77_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="jobdbmodel",
            index=models.Index(fields=["name"], name="async_job_name_46c5c8_idx"),
        ),
    ]
